language: node_js
node_js:
    - '8.10'
branches:
    only:
        - master

before_install:
      - docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD $DOCKER_REGISTRY
      
install:
      - docker build -t podnoms.azurecr.io/podnoms.web .
      - docker push podnoms.azurecr.io/podnoms.web
