language: node_js
node_js:
    - '8.10'
branches:
    only:
        - master

before_install:
      - docker login --username=$DOCKER_REGISTRY_USER --password=$DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
      
install:
      - docker build -t podnoms.azurecr.io/podnoms.api .
      - docker push podnoms.azurecr.io/podnoms.api
